apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fraud-service"
  labels:
    app: "fraud-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "fraud-service"
  template:
    metadata:
      labels:
        app: "fraud-service"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "fraud-service"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: node
        image: ${SERVICE_FRAUD_SERVICE_IMAGE_NAME}
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_VERSION
          value: "1.0.0"
        - name: AZURE_CLIENT_ID
          value: ${AZURE_AKS_IDENTITY_CLIENT_ID}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "512m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
            