kind: Service
apiVersion: v1
metadata:
  name: "public-api-service"
  labels:
    app: "public-api-service"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: "public-api-service"