name: "CI"

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-20.04
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Dapr
        run: |
          wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash

      - name: Setup Local
        run: make start-local

      - name: Deploy Local
        run: make deploy-local

      - name: Test
        run: |
          kubectl port-forward service/public-api-service 8080:80 --pod-running-timeout=3m0s &
          make test-e2e
